### ISSUE TITLE
Label only in autocomplete dropdown

### ISSUE THREAD

**Issue by ecgreb** [mapzen/pelias-android-sdk#13]
https://github.com/mapzen/eraser-map/issues/85

Currently the autocomplete widget is using label + city + admin to populate the drop down list. @missinglink I am assuming this should use the label field only?

https://github.com/mapzen/pelias-android-sdk/blob/master/src/main/java/com/mapzen/pelias/SimpleFeature.java#L185

**Comment by missinglink** [comment]
I would suggest using the `label` field as-is.

we have a [bunch of tests](https://github.com/pelias/api/blob/master/test/unit/helper/labelGenerator.js) covering label generation if you're interested in seeing some of the combinations.

feedback is super welcome because we're still trying to figure out what's best for the user, we try to keep them as short as possible so they will fit on portrait screens ;)

**Comment by ecgreb** [comment]
Will do.
